/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Staffs;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.io.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author John Paul
 */
public class Staff_Profile_main extends javax.swing.JFrame {

    /**
     * Creates new form Staffs_Profile
     */
    public Staff_Profile_main(){
        initComponents();
         setLocationRelativeTo(null);
        
        this.setShape(new RoundRectangle2D.Double(0, 0, (850), 
        (480), 25, 25));
        
        left_panel_bg();
        right_panel_bg();
      
    }
     void left_panel_bg(){
        ImageIcon lpbg = new ImageIcon("lpbg.png");
        Image image = lpbg.getImage(); // transform it 
        Image newimg = image.getScaledInstance(570, 480,  java.awt.Image.SCALE_DEFAULT); // scale it the smooth way  
        lpbg = new ImageIcon(newimg);
        lp_bg.setIcon(lpbg);
    }
    void right_panel_bg(){

        ImageIcon rpbg = new ImageIcon("rpbg.png");
        Image image = rpbg.getImage(); // transform it 
        Image newimg = image.getScaledInstance(570, 480,  java.awt.Image.SCALE_DEFAULT); // scale it the smooth way  
        rpbg = new ImageIcon(newimg);
        rp_bg.setIcon(rpbg);
                
    }
    
    void move_pf_file() throws FileNotFoundException{
        
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File("D:\\Users\\Backup\\Desktop"));
        int response = jfc.showOpenDialog(null);
        String fildest = System.getProperty("user.dir");
        
        if(response == JFileChooser.APPROVE_OPTION){
            File file = new File(jfc.getSelectedFile().getAbsolutePath());
            System.out.println(file);
            
            if(file.exists()){
                File destfile = new File(fildest + File.separator + file.getName());
                
                try(InputStream is = new FileInputStream(file);
                        OutputStream os = new FileOutputStream(destfile)){
                    
                    int len;
                    float srcfsize = is.available() / 1000.0f;
                    float totalcopied = 0.0f;
                    byte[] byt = new byte[1024];
                    while( (len = is.read(byt)) > 0){
                        os.write(byt, 0, len);
                        totalcopied += len;
                        System.out.println("\rcopied" + totalcopied / 1000.0f + "kb/" + file + "kb");
                        Thread.sleep(5);
                    }
                    
                    
                }catch(IOException | InterruptedException e){
                    e.printStackTrace();
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Log_out = new javax.swing.JButton();
        icon_prof = new javax.swing.JLabel();
        staff_name = new javax.swing.JLabel();
        lp_bg = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f_n = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        p_no = new javax.swing.JLabel();
        Edit_prof = new javax.swing.JButton();
        edit_name = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        F_Name = new javax.swing.JLabel();
        F_Name1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        rp_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Log_out.setBackground(new java.awt.Color(255, 204, 102));
        Log_out.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Log_out.setForeground(new java.awt.Color(255, 255, 255));
        Log_out.setText("Log out");
        Log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_outMouseClicked(evt);
            }
        });
        jPanel1.add(Log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        icon_prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/profile icon.png"))); // NOI18N
        icon_prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_profMouseClicked(evt);
            }
        });
        jPanel1.add(icon_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, 80));

        staff_name.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        staff_name.setText("Staff name");
        jPanel1.add(staff_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel1.add(lp_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 480));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        profile.setText("Profile");
        jPanel2.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 70, -1));

        f_n.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_n.setText("Frist Name:");
        jPanel2.add(f_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 294, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        p_no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        p_no.setText("Phone num:");
        jPanel2.add(p_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        Edit_prof.setBackground(new java.awt.Color(255, 204, 102));
        Edit_prof.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Edit_prof.setForeground(new java.awt.Color(255, 255, 255));
        Edit_prof.setText("Edit Profile");
        Edit_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_profActionPerformed(evt);
            }
        });
        jPanel2.add(Edit_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 406, -1, -1));

        edit_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/seat.png"))); // NOI18N
        edit_name.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                edit_nameMouseDragged(evt);
            }
        });
        jPanel2.add(edit_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        Password.setText("jPasswordField1");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 294, -1));

        F_Name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        F_Name.setText("First Name");
        jPanel2.add(F_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        F_Name1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        F_Name1.setText("Last Name");
        jPanel2.add(F_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel2.setText("Email:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 30));

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 131, -1));

        rp_bg.setPreferredSize(new java.awt.Dimension(570, 480));
        jPanel2.add(rp_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 570, 480));

        setSize(new java.awt.Dimension(850, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Edit_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_profActionPerformed

    }//GEN-LAST:event_Edit_profActionPerformed

    private void Log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_outMouseClicked
       this.dispose();
    }//GEN-LAST:event_Log_outMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            new Movie_List().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Staff_Profile_main.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void icon_profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_profMouseClicked
        try {      
            move_pf_file();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Staff_Profile_main.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_icon_profMouseClicked

    private void edit_nameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_nameMouseDragged
       Staff_Name sb= new Staff_Name();
        sb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_edit_nameMouseDragged

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit_prof;
    private javax.swing.JLabel F_Name;
    private javax.swing.JLabel F_Name1;
    private javax.swing.JButton Log_out;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton back;
    private javax.swing.JLabel edit_name;
    private javax.swing.JTextField email;
    private javax.swing.JLabel f_n;
    private javax.swing.JLabel icon_prof;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lp_bg;
    private javax.swing.JLabel p_no;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel rp_bg;
    private javax.swing.JLabel staff_name;
    // End of variables declaration//GEN-END:variables
}